<?php

define('JQUERY_WEEK_CALENDAR_PATH', 'sites/all/libraries/jquery-week-calendar');

/**
 * Implements hook_permission().
 */
function jquery_week_calendar_permission(){
  return array(
    'administer jquery week calendar' => array(
      'title' => t('Administer Jquery Week Calendar'), 
      'description' => t('Perform administration tasks for Jquery Week Calendar module.'),
    ),
    'use jquery week calendar' => array(
      'title' => t('Use Jquery Week Calendar to Insert/Edit Nodes'), 
      'description' => t('Use Jquery Week Calendar module to create/edit nodes.'),
    ),
    'view jquery week calendar' => array(
      'title' => t('Use Jquery Week Calendar to View Nodes'), 
      'description' => t('Use Jquery Week Calendar module to view nodes.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function jquery_week_calendar_menu(){
  $items['admin/config/user-interface/jquery-week-calendar'] = array(
    'title' => 'Jquery Week Calendar Settings',
    'page callback' => 'jquery_week_calendar_settings',
    'access arguments' => array('administer jquery week calendar'),
    'file' => 'jquery_week_calendar.admin.inc'
  );
  $items['admin/config/user-interface/jquery-week-calendar/list'] = array(
    'title' => 'Jquery Week Calendar Sample',
    'page callback' => 'jquery_week_calendar_settings',
    'access arguments' => array('administer jquery week calendar')
  );
  $items['admin/config/user-interface/jquery-week-calendar/add'] = array(
    'title' => 'Jquery Week Calendar Sample',
    'page callback' => 'jquery_week_calendar_settings',
    'access arguments' => array('administer jquery week calendar')
  );
  $items['admin/config/user-interface/jquery-week-calendar/sample'] = array(
    'title' => 'Jquery Week Calendar Sample',
    'page callback' => 'jquery_week_calendar_settings',
    'access arguments' => array('administer jquery week calendar')
  );
  return $items;
}

/***** UTILITY FUNCTIONS *****/

/**
 * Retrieves the list of available profiles
 */
function jquery_week_calendar_get_profiles(){
  
}

function jquery_week_calendar_load_profile($pid = NULL){
  $profile = new stdClass();
  if($pid = NULL){
    
  }
  return $profile;
}

function jquery_week_calendar_delete_profile($pid = NULL){
  
}
